### ISSUE TITLE
SweeperServer terminating with invalid query params

### ISSUE THREAD

**Issue by stephenlacy** [alexfilatov/guardian_redis#2]
My application:

```elixir
def start(_type, _args) do
    children = [
      GuardianRedis.Redix,
      {Guardian.DB.Token.SweeperServer, []}
   ]
end
```

The sweep cycle terminates with this error:
```elixir
iex(1)> [error] GenServer Guardian.DB.Token.SweeperServer terminating
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(1, nil)
    (guardian_redis 0.1.0) lib/repo.ex:130: GuardianRedis.Repo.query_param/2
    (guardian_redis 0.1.0) lib/repo.ex:72: GuardianRedis.Repo.delete_all/2
    (guardian_db 2.1.0) lib/guardian/db/token/sweeper.ex:12: Guardian.DB.Token.Sweeper.sweep/1
    (guardian_db 2.1.0) lib/guardian/db/token/sweeper_server.ex:54: Guardian.DB.Token.SweeperServer.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :sweep
State: %{interval: 3600000, timer: #Reference<0.42768697.17814209.1360>}
```

The value of `query` and `params` in `query_param` is:
```elixir
query = Ecto.Query<from t0 in {"sessions", Guardian.DB.Token}, where: t0.exp < ^1624510954>

params = :sub

```

This line returns nil:
```elixir
|> Enum.find(fn i -> i |> elem(1) |> elem(1) == param end)
```

**Comment by alexfilatov** [comment]
Hey @stevelacy , thanks for submitting the issue. If you use guardian_redis, you don’t need a sweeper server provided by guardian.db  as it sweeps token automatically using internal redis timeout mechanism. 
Please let me know if that helps.

**Comment by stephenlacy** [comment]
Thanks for clarifying!
